server:
  port: 8080
application:
  jwt-secret: "JWTSecretKey"
  jwt-expiration-milliseconds: "600000"
  session-time: 5
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true